# Avent of Code 2021

### HowTo download input file
* get session string from browser cookie (https://github.com/wimglenn/advent-of-code-wim/issues/1)
* set up session token in hidden local file ".aoc_token" <- add to .gitignore
* set up `eyport AOC_SESSION=<session string>`

In [2]:
%%bash
source ../.aoc_token
curl 'https://adventofcode.com/2021/day/6/input' -X GET -H "Cookie: session=$AOC_SESSION" > ../data/day06.txt
touch ../data/day06_test.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9294  100  9294    0     0  58452      0 --:--:-- --:--:-- --:--:-- 58822


In [69]:
### Day 5, part 1
import numpy as np
file = open("../data/day05_test.txt", "r")

input = ()
lines = []
xs = []
ys = []
for row in file:
  clean_row = row.rstrip('\n')
  a,b = clean_row.split(' -> ')
  lines.append([[int(x) for x in a.split(',')],[int(x) for x in b.split(',')]])
  xs.append(lines[-1][0][0])
  xs.append(lines[-1][1][0])
  ys.append(lines[-1][0][1])
  ys.append(lines[-1][1][1])
file.close()

max_x = max(xs) + 1
max_y = max(ys) + 1
print(f'making matrix with dims: {max_x}, {max_y}')
df = np.zeros((max_x, max_y))

for line in lines:
  [[x1,y1],[x2,y2]] = line
  x_direction = 1 if x2 > x1 else -1
  x_end = x2 +1 if x_direction == 1 else x2 - 1
  y_direction = 1 if y2 > y1 else -1
  y_end = y2 +1 if y_direction == 1 else y2 - 1
  #flipped x,y in numpy matrix so viz matches A0C example orientation
  if (x1 == x2 and y1 == y2):
      df[y1][x1] += 1
  elif x1 == x2:
    for i in range(y1,y_end,y_direction):
      df[i][x1] += 1
  elif y1 == y2:
    for i in range(x1,x_end,x_direction):
      df[y1][i] += 1
  else:
    #not doing diagonals right now
    pass
points = df > 1.0 
print(df)
print(sum(sum(points)))


making matrix with dims: 10, 10
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 2. 1. 1. 1. 2. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]
5


In [67]:
### Day 5, part 2
import numpy as np
file = open("../data/day05.txt", "r")

input = ()
lines = []
xs = []
ys = []
for row in file:
  clean_row = row.rstrip('\n')
  a,b = clean_row.split(' -> ')
  lines.append([[int(x) for x in a.split(',')],[int(x) for x in b.split(',')]])
  xs.append(lines[-1][0][0])
  xs.append(lines[-1][1][0])
  ys.append(lines[-1][0][1])
  ys.append(lines[-1][1][1])
file.close()


max_x = max(xs) + 1
max_y = max(ys) + 1
print(f'making df of dims {max_x}, {max_y}')
df = np.zeros((max_x, max_y))

for line in lines:
  [[x1,y1],[x2,y2]] = line
  x_direction = 1 if x2 > x1 else -1
  x_end = x2 +1 if x_direction == 1 else x2 - 1
  y_direction = 1 if y2 > y1 else -1
  y_end = y2 +1 if y_direction == 1 else y2 - 1
  if (x1 == x2 and y1 == y2):
      df[y1][x1] += 1
  elif x1 == x2:
    for i in range(y1,y_end,y_direction):
      df[i][x1] += 1
  elif y1 == y2:
    for i in range(x1,x_end,x_direction):
      df[y1][i] += 1
  else:
    for i, j in zip(range(x1,x_end,x_direction),range(y1,y_end,y_direction)):
      df[j][i] += 1
points = df > 1.0 
print(df)
print(sum(sum(points)))


making df of dims 990, 990
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
15463


In [206]:
### Day 4, part 1
import pandas as pd
file = open("../data/day04.txt", "r")
draw_info = file.readline()
draws = [int(draw) for draw in draw_info.split(',')]
# print(draws)
card_info = file.readlines()
count = 0
cards = []
hits = []
end_point = len(card_info)
for line_number, line in enumerate(card_info):
  clean_line = line.rstrip('\n')
  # print(f'evaluating clean_line:\'{clean_line}\'')
  if not clean_line:
    # print(f'starting card {count}')
    i = 0
    if count > 0:
      # print(df)
      cards.append(df)
      # print(cards)
      continue
    else:
      count +=1
  else:
    numbers = clean_line.split()
    # print(numbers)
    if i == 0:
      df = pd.DataFrame(columns=(range(len(numbers))))
      hits.append(pd.DataFrame(columns=(range(len(numbers)))))
    df.loc[i]  = [int(number) for number in numbers]
    # print(df)
    i += 1
    if line_number == end_point - 1:
      cards.append(df)
file.close()

def is_winning_card(marks):
  column_wins = False
  row_wins = False
  for i in marks.columns:
    if marks[:][i].all():
      column_wins = True
  # for i in marks.index:
  #   if marks.iloc[i, :].all():
  #     row_wins = True
  # above comment is functionally equivalent to below using
  # matrix reduction to rows using axis parameter, check if any rows have all True
  if marks.all(axis=1).any():
    row_wins = True
  return True if (row_wins or column_wins) else False
called = []
won = False
for turn, draw in enumerate(draws):
  if won:
    break
  called.append(draw)
  for index, card in enumerate(cards):
    marked_card = card.isin(called)
    # print(marked_card)
    hits[index] = marked_card
    if is_winning_card(marked_card):
      won = True
      print(f'card {index} won on turn {turn} with winning draw {draw}')
      # https://stackoverflow.com/questions/38733477/whats-the-best-way-to-sum-all-values-in-a-pandas-dataframe
      # df.sum().sum() ignores nan and returns a float whereas df.values.sum() returns nan
      # Filtered dataframes have nan in the filtered cells so use df.sum().sum() for this use case
      sum = cards[index][~marked_card].sum().sum()
      final_score = sum * draw
      print(f'Final Score: {final_score}')
      break


card 90 won on turn 13 with winning draw 10
Final Score: 10680


In [221]:
### Day 4, part 2
import pandas as pd
file = open("../data/day04.txt", "r")
draw_info = file.readline()
draws = [int(draw) for draw in draw_info.split(',')]
# print(draws)
card_info = file.readlines()
count = 0
cards = []
hits = []
end_point = len(card_info)
for line_number, line in enumerate(card_info):
  clean_line = line.rstrip('\n')
  # print(f'evaluating clean_line:\'{clean_line}\'')
  if not clean_line:
    # print(f'starting card {count}')
    i = 0
    if count > 0:
      # print(df)
      cards.append(df)
      # print(cards)
      continue
    else:
      count +=1
  else:
    numbers = clean_line.split()
    # print(numbers)
    if i == 0:
      df = pd.DataFrame(columns=(range(len(numbers))))
      hits.append(pd.DataFrame(columns=(range(len(numbers)))))
    df.loc[i]  = [int(number) for number in numbers]
    # print(df)
    i += 1
    if line_number == end_point - 1:
      cards.append(df)
file.close()

def is_winning_card(marks):
  column_wins = False
  row_wins = False
  for i in marks.columns:
    if marks[:][i].all():
      column_wins = True
  # for i in marks.index:
  #   if marks.iloc[i, :].all():
  #     row_wins = True
  # above comment is functionally equivalent to below using
  # matrix reduction to rows using axis parameter, check if any rows have all True
  if marks.all(axis=1).any():
    row_wins = True
  return True if (row_wins or column_wins) else False
called = []
# Tried using an OrderedDict for winning_masks but couldn't get .setdefault syntax right 
winning_masks = {}
winning_draws = {}
winners = []
for turn, draw in enumerate(draws):
  called.append(draw)
  # print(f'Turn {turn}')
  for index, card in enumerate(cards):
    marked_card = card.isin(called)
    # print(marked_card)
    hits[index] = marked_card
    if is_winning_card(marked_card):
      won = True
      if index not in winning_masks.keys():
        # print(f'card {index} won on turn {turn} with winning draw {draw}')
        winners.append(index)
        winning_masks[index] = marked_card
        winning_draws[index] = draw
  if len(winners) == len(cards):
    break

# print(winners)
winner = winners[-1]
# print(cards[winner])
# print(cards[winner][~winning_masks[winner]])
sum = cards[winner][~winning_masks[winner]].sum().sum()
final_score = sum * winning_draws[winner]
print(f'Final Score for last card to win: {final_score}')

Final Score for last card to win: 31892


In [222]:
### scratch space
import pandas as pd
file = open("../data/day03_test.txt", "r")
string_length = 5  # 5 for test data
data = file.readlines()
file.close()

df = pd.DataFrame(columns=(range(string_length)))
for i, line in enumerate(data):
  clean_line = line.rstrip('\n')
  df.loc[i]  = [char for char in clean_line]
mask = [True] * len(df.index)
# print(len(df.index))
# #print(df[mask])
# print(len(df[mask].index))

In [20]:
### Day 3, part 1
import pandas as pd
file = open("../data/day03.txt", "r")
string_length = 12  # 5 for test data
data = file.readlines()
file.close()
gamma_data = ''
epsilon_data = ''
df = pd.DataFrame(columns=(range(string_length)))
for i, line in enumerate(data):
  clean_line = line.rstrip('\n')
  df.loc[i]  = [char for char in clean_line]
for j in range(string_length):
  gamma_data += df[j].value_counts().idxmax()
  epsilon_data += df[j].value_counts().idxmin()
gamma = int(gamma_data, 2)
epsilon = int(epsilon_data, 2)
power = gamma * epsilon
print(power) 

1540244


In [107]:
### Day 3, part 2
import pandas as pd
file = open("../data/day03.txt", "r")
string_length = 12  # 5 for test data; 12 for input data
data = file.readlines()
file.close()
gamma_data = ''
epsilon_data = ''
df = pd.DataFrame(columns=(range(string_length)))
for i, line in enumerate(data):
  clean_line = line.rstrip('\n')
  df.loc[i]  = [char for char in clean_line]

def find_rating(df, tie_breaker, mask, count, method):
  if len(df[mask].index) == 1:
    rating = ''
    for j in range(string_length):
      rating += df[mask][j].values[0]
    print(f'converged at round {count}, on {rating} or decimal {int(rating, 2)}')
    return int(rating, 2)
  else:
    if method == 'max':
      criteria = df[mask][count].mode()
      criteria = tie_breaker if (len(criteria) > 1) else df[mask][count].mode()[0]
    else:
      criteria = df[mask][count].value_counts().idxmin()
      criteria = tie_breaker if (len(criteria) > 1) else df[mask][count].value_counts().idxmin()
    addnl_mask = df[mask][count] == criteria
    new_mask = addnl_mask if all(mask) else (mask & addnl_mask)
    # print(f'matrix to assess column {count + 1}, chosen by {criteria}')
    # print(df[new_mask])
    return find_rating(df, tie_breaker, new_mask, count+1, method)
mask = [True] * len(df.index)
o_rate = find_rating(df, '1', mask, 0, 'max')
c_rate = find_rating(df, '0', mask, 0, 'min')
life_support_rating = o_rate * c_rate
print(life_support_rating)

converged at round 12, on 010010001001 or decimal 1161
converged at round 9, on 111000100101 or decimal 3621
4203981


In [20]:
### Day 2, part 1
import re

file = open("../data/day02.txt", "r")
data = file.readlines()
file.close()
position = 0
depth = 0
for line in data:
  parse = re.search('(\w+) (\d)$', line)
  if parse.group(1) == "forward":
    position += int(parse.group(2))
  elif parse.group(1) == "up":
    depth -= int(parse.group(2))
  elif parse.group(1) == "down":
    depth += int(parse.group(2))
  else:
    print(f'did find known keyword in {line}')
print(position*depth)

1635930


In [23]:
### Day 2, part 2
file = open("../data/day02.txt", "r")
data = file.readlines()
file.close()
position = 0
depth = 0
aim = 0
for line in data:
  parse = re.search('(\w+) (\d)$', line)
  if parse.group(1) == "forward":
    position += int(parse.group(2))
    depth += aim * int(parse.group(2))
  elif parse.group(1) == "up":
    aim -= int(parse.group(2))
  elif parse.group(1) == "down":
    aim += int(parse.group(2))
  else:
    print(f'did find known keyword in {line}')
print(position*depth)

1781819478


In [1]:
### Day 1, part 1
file = open("../data/day01.txt", "r")
data = file.readlines()
file.close()
increase_count = 0
for x,y in zip(data, data[1:]):
  if int(y) > int(x):
    increase_count += 1
print(increase_count)

1715


In [32]:
### Day 1, part 2
file = open("../data/day01.txt", "r")
data = file.readlines()
file.close()
increase_count = 0
for x,y in zip(data, data[3:]):
  if int(y) > int(x):
    increase_count += 1
print(increase_count)

1739


## Github setup
* create repo in github
* git init -b main
* git commit -m "first commit"
* git remote add origin https://github.com/jlchang/AoC2021_python.git
* git push origin main